# -*- coding: utf-8 -*-
# Copyright (C) 2016-Today: GRAP (http://www.grap.coop)
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).


- !record {model: product.pricelist, id: pricelist_10_discount}:
    name: Sale Price List With 10% discount
    type: sale

- !record {model: product.pricelist.version, id: pricelist_version_10_discount}:
    name: Sale Price List Version With 10% discount
    pricelist_id: pricelist_10_discount

- !record {model: product.pricelist.item, id: pricelist_item_10_discount}:
    name: Sale Price List Item With 10% discount
    price_version_id: pricelist_version_10_discount
    base: !eval (ref('product.list_price'))
    price_discount: -0.10
