# -*- encoding: utf-8 -*-
##############################################################################
#
#    Sale - eShop for Odoo
#    Copyright (C) 2014 GRAP (http://www.grap.coop)
#    @author Sylvain LE GAL (https://twitter.com/legalsylvain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

- !record {model: product.product, id: product_banana}:
    name: Banana
    categ_id: product.product_category_all
    list_price: 2.45
    eshop_category_id: category_fruit
    eshop_minimum_qty: 0.5
    eshop_rounded_qty: 0.1
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Banana
    sale_ok: True
    type: consu

- !record {model: product.product, id: product_strawberry}:
    name: Strawberry (250 gr)
    categ_id: product.product_category_all
    list_price: 3.10
    eshop_category_id: category_fruit
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    description_sale: Description of Strawberry. 250 gram container
    sale_ok: True
    type: consu

- !record {model: product.product, id: product_apple}:
    name: Apple
    list_price: 2.45
    eshop_category_id: category_fruit
    eshop_minimum_qty: 1.0
    eshop_rounded_qty: 0.2
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Apple
    sale_ok: True
    type: consu


- !record {model: product.product, id: product_potato}:
    name: Potato
    list_price: 1.95
    eshop_category_id: category_vegetable
    eshop_minimum_qty: 1.0
    eshop_rounded_qty: 0.5
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Potato
    sale_ok: True
    type: consu

- !record {model: product.product, id: product_leek}:
    name: Leek
    list_price: 2.90
    eshop_category_id: category_vegetable
    eshop_minimum_qty: 0.4
    eshop_rounded_qty: 0.2
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Leek
    sale_ok: True
    type: consu

- !record {model: product.product, id: product_onion}:
    name: Onion
    list_price: 3.00
    eshop_category_id: category_vegetable
    eshop_minimum_qty: 0.5
    eshop_rounded_qty: 0.1
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Onions
    sale_ok: True
    type: consu

- !record {model: product.product, id: product_garlic}:
    name: Garlic
    list_price: 7.00
    eshop_category_id: category_vegetable
    eshop_minimum_qty: 0.1
    eshop_rounded_qty: 0.02
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Garlic
    sale_ok: True
    type: consu

- !record {model: product.product, id: product_pepper}:
    name: Pepper
    list_price: 7.00
    eshop_category_id: category_vegetable
    eshop_minimum_qty: 0.4
    eshop_rounded_qty: 0.1
    uom_id: product.product_uom_kgm
    uom_po_id: product.product_uom_kgm
    uos_id: product.product_uom_kgm
    description_sale: Description of Pepper
    sale_ok: True
    type: consu


- !record {model: product.product, id: product_without_image}:
    name: Product Without Image
    list_price: 100.00
    eshop_category_id: category_without_image
    eshop_minimum_qty: 1.0
    eshop_rounded_qty: 1.0
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    uos_id: product.product_uom_unit
    sale_ok: True
    type: consu
